# Generated by Django 5.2.3 on 2025-06-18 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210918_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_db',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question_db',
            name='optionA',
        ),
        migrations.RemoveField(
            model_name='question_db',
            name='optionB',
        ),
        migrations.RemoveField(
            model_name='question_db',
            name='optionC',
        ),
        migrations.RemoveField(
            model_name='question_db',
            name='optionD',
        ),
        migrations.AddField(
            model_name='question_db',
            name='question_type',
            field=models.CharField(choices=[('SUBJECTIVE', 'Subjective')], default='SUBJECTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 18, 13, 36, 740980)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 18, 13, 36, 740980)),
        ),
    ]
