# Generated by Django 5.2.3 on 2025-06-18 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_question_db_answer_remove_question_db_optiona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 18, 42, 31, 418831)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 18, 42, 31, 418831)),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
