# Generated by Django 5.2.3 on 2025-06-21 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Upload an image to accompany this question (optional)', null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 15, 16, 56, 645119)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 15, 16, 56, 645119)),
        ),
    ]
