# Generated by Django 5.2.3 on 2025-06-21 09:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_exam_model_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 15, 40, 39, 278146)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 15, 40, 39, 278146)),
        ),
        migrations.CreateModel(
            name='ReferenceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Reference text answer', null=True)),
                ('image_answer', models.ImageField(blank=True, help_text='Reference handwritten answer image', null=True, upload_to='reference_answers/')),
                ('ocr_text', models.TextField(blank=True, help_text='OCR extracted text from reference image', null=True)),
                ('tfidf_vector', models.JSONField(blank=True, help_text='TF-IDF vector for similarity comparison', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(limit_choices_to={'groups__name': 'Professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_answers', to='main.question_db')),
            ],
            options={
                'verbose_name': 'Reference Answer',
                'verbose_name_plural': 'Reference Answers',
                'unique_together': {('question', 'professor')},
            },
        ),
    ]
