# Generated by Django 5.2.3 on 2025-06-18 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_question_db_answer_remove_question_db_optiona_and_more'),
        ('student', '0002_auto_20200826_1637'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_question',
            name='choice',
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='completed',
            field=models.IntegerField(default=int),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='score',
            field=models.IntegerField(default=int),
        ),
        migrations.CreateModel(
            name='SubjectiveAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('image_answer', models.ImageField(blank=True, null=True, upload_to='subjective_answers/')),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question_db')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
