# Generated by Django 5.2.3 on 2025-06-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_exam_model_end_time_and_more'),
        ('student', '0003_remove_stu_question_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_question',
            name='original_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_questions', to='main.question_db'),
        ),
    ]
