# Generated by Django 5.2.3 on 2025-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_stu_question_original_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectiveanswer',
            name='feedback',
            field=models.TextField(blank=True, help_text='Automated feedback based on TF-IDF analysis', null=True),
        ),
        migrations.AddField(
            model_name='subjectiveanswer',
            name='score',
            field=models.FloatField(default=0.0, help_text='TF-IDF similarity score (0-100)'),
        ),
    ]
