# Generated by Django 5.2.3 on 2025-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_subjectiveanswer_feedback_subjectiveanswer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectiveanswer',
            name='score',
        ),
        migrations.AddField(
            model_name='subjectiveanswer',
            name='marks',
            field=models.IntegerField(default=0, help_text='Marks awarded (0-5)'),
        ),
    ]
